-- migration: create links table
CREATE TABLE IF NOT EXISTS links (
  id TEXT PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  target_url TEXT NOT NULL,
  click_count INTEGER NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN NOT NULL DEFAULT 1
);
